### ISSUE TITLE
Internationalisation question

### ISSUE THREAD

**Issue by hvitis** [PxlSyl/tailwind-nextjs-starter-blog-i18n#3]
**Is your feature request related to a problem? Please describe.**
Hey! I have seen that there is a fallback language. Does it mean that this repo is for a bilingual blog or multilingual?

**Comment by PxlSyl** [comment]
Hello! It is programmed as a template with a base of two languages, but it can easily be extended to other languages (3, 4, 5 or even more) by modifying a few files. (I made sure that it wasn't that complicated to set up) 

I plan to explain this in a future article which will be on the demo :)

That said, I think that two languages will cover most cases of uses: English as a conventional language and technical language, and the natural language of the blogger. More could be a bit overkill for a blog lol, but if you need three, it's totally possible!

The fallback language is actually designed as the language without a locale in the url, like this : "yoursite/" instead of "yoursite/en" and is set up to english. But it can be set up to any language

**Comment by PxlSyl** [comment]
Well, if you have any new ideas, or see any bugs, or things that should be improved, that's totally welcome!
